// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ2Kn8tbSN3Du3qssyfPIfXg8HMJ5225w',
    appId: '1:412482129058:web:360a02b8e44f63a3d19bfb',
    messagingSenderId: '412482129058',
    projectId: 'wrapshots-ac38a',
    authDomain: 'wrapshots-ac38a.firebaseapp.com',
    storageBucket: 'wrapshots-ac38a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgOpd9Rv0eifdztK5Jva-U7WPxNftStA',
    appId: '1:412482129058:android:ec40e3df2a1d59b6d19bfb',
    messagingSenderId: '412482129058',
    projectId: 'wrapshots-ac38a',
    storageBucket: 'wrapshots-ac38a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAt5QHt2Jjt29uGZ46xnyO8vfqx-0RQQ4',
    appId: '1:412482129058:ios:ef8f2825e824813cd19bfb',
    messagingSenderId: '412482129058',
    projectId: 'wrapshots-ac38a',
    storageBucket: 'wrapshots-ac38a.appspot.com',
    iosClientId: '412482129058-9v2b9fml4av394k9elnkl5065ev47ene.apps.googleusercontent.com',
    iosBundleId: 'com.example.wrapshots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAt5QHt2Jjt29uGZ46xnyO8vfqx-0RQQ4',
    appId: '1:412482129058:ios:ef8f2825e824813cd19bfb',
    messagingSenderId: '412482129058',
    projectId: 'wrapshots-ac38a',
    storageBucket: 'wrapshots-ac38a.appspot.com',
    iosClientId: '412482129058-9v2b9fml4av394k9elnkl5065ev47ene.apps.googleusercontent.com',
    iosBundleId: 'com.example.wrapshots',
  );
}
